# This prank for school.
import time
def Wait(a): # Loading yea.
	print("###")
	time.sleep(a)
	print("H##")
	time.sleep(a)
	print("HA#")
	time.sleep(a)
	print("HAC#")
	time.sleep(a)
	print("HACK")
print("Welcome 2 terminal HACKING")
Erere = int(input("1. Start 2. Exit "))
if Erere == 1:
	SoManyUser = str(input("Type here who need hack: "))
	print("Bluetooh online checking")
	time.sleep(2)
	print("Bluetooh online.")
	time.sleep(2)
	print("Scanning.")
	Wait(1)
	print("Hacking all bluetooh devices")
	Wait(3)
	print("Finded: " + SoManyUser)
	time.sleep(1)
	print("Hacking instagram.")
	time.sleep(1)
	print("Hacking google history")
	time.sleep(1)
	print("Email: " + SoManyUser + "@prank.com")
	time.sleep(1)
	print("Password: 756345437123")
	time.sleep(1)
	print("Coping all photos")
	Wait(1)
	print("Completed.")
	time.sleep(1)
	print("FULL HACK COMPLETED!")
	time.sleep(1)
	print("This is prank lol.")
else:
	print("Shutdown.....")